import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import {
  ACTION_KIND,LIFE_STATE,TARGET_TYPE,advanceClosedRound,createHoldDeclaration,
  createRosterAbilityDeclaration,createTeamBattleState,getArchetype,simulateRosterRoundPackage
} from '../src/index.js';
const here=dirname(fileURLToPath(import.meta.url));const root=resolve(here,'..');
class Peer{
  constructor(name){this.name=name;this.ws=null;this.messages=[];this.waiters=[];}
  async connect(url){this.ws=new WebSocket(url);this.ws.addEventListener('message',e=>{const msg=JSON.parse(String(e.data));const i=this.waiters.findIndex(w=>w.kind===msg.kind&&(!w.predicate||w.predicate(msg)));if(i>=0){const[w]=this.waiters.splice(i,1);clearTimeout(w.timer);w.resolve(msg);}else this.messages.push(msg);});await new Promise((res,rej)=>{const tm=setTimeout(()=>rej(new Error(`${this.name} connect timeout`)),3000);this.ws.addEventListener('open',()=>{clearTimeout(tm);res();},{once:true});this.ws.addEventListener('error',()=>{clearTimeout(tm);rej(new Error(`${this.name} socket error`));},{once:true});});return this;}
  send(kind,payload={}){this.ws.send(JSON.stringify({kind,...payload}));}
  waitFor(kind,predicate=null,timeout=4000){const i=this.messages.findIndex(m=>m.kind===kind&&(!predicate||predicate(m)));if(i>=0)return Promise.resolve(this.messages.splice(i,1)[0]);return new Promise((res,rej)=>{const w={kind,predicate,resolve:res,timer:null};w.timer=setTimeout(()=>{const x=this.waiters.indexOf(w);if(x>=0)this.waiters.splice(x,1);rej(new Error(`${this.name} timed out waiting for ${kind}; queued=${this.messages.map(m=>m.kind).join(',')}`));},timeout);this.waiters.push(w);});}
  close(){try{this.ws?.close();}catch{}}
}
async function startServer(){const child=spawn(process.execPath,['server/relay-server.cjs'],{cwd:root,env:{...process.env,PORT:'0'},stdio:['ignore','pipe','pipe']});let stderr='';child.stderr.on('data',d=>stderr+=String(d));const port=await new Promise((res,rej)=>{const tm=setTimeout(()=>rej(new Error(`server start timeout: ${stderr}`)),5000);child.stdout.on('data',d=>{const m=String(d).match(/listening on (\d+)/);if(m){clearTimeout(tm);res(Number(m[1]));}});child.once('exit',code=>{clearTimeout(tm);rej(new Error(`server exited ${code}: ${stderr}`));});});return{child,url:`ws://127.0.0.1:${port}/ws`};}
async function connectPair(url,label){const A=await new Peer(`${label}-A`).connect(url),B=await new Peer(`${label}-B`).connect(url);await A.waitFor('hello_ack');await B.waitFor('hello_ack');return{A,B};}
async function createAndDraft({url,teamSize,label,bans=0,pickPlan=null}){const{A,B}=await connectPair(url,label);const roomId=`${label}-${Date.now()}-${Math.floor(Math.random()*10000)}`;A.send('create_room',{id:roomId,teamSize,draftBansPerPlayer:bans});assert.equal((await A.waitFor('room_joined')).side,'A');B.send('join_room',{id:roomId});assert.equal((await B.waitFor('room_joined')).side,'B');await A.waitFor('room_locked');await B.waitFor('room_locked');let state=(await A.waitFor('draft_state')).state;while(!state.complete){const before=`${state.phase}:${state.banIndex}:${state.pickIndex}`,actor=state.turnSide==='A'?A:B;let archetype=state.phase==='BAN'?state.available[0]:(pickPlan?.[state.turnSide]?.[state.picks[state.turnSide].length]??state.available[0]);actor.send(state.phase==='BAN'?'draft_ban':'draft_pick',{archetype});state=(await A.waitFor('draft_state',m=>`${m.state.phase}:${m.state.banIndex}:${m.state.pickIndex}`!==before)).state;}const finalB=await B.waitFor('draft_state',m=>m.state.complete===true);assert.deepEqual(finalB.state.picks,state.picks);const startedA=await A.waitFor('match_started'),startedB=await B.waitFor('match_started');assert.equal(startedA.matchId,startedB.matchId);assert.deepEqual(startedA.teamA,startedB.teamA);assert.deepEqual(startedA.teamB,startedB.teamB);assert.equal(startedA.config.teamSize,teamSize);return{A,B,roomId,started:startedA};}
function holdsFor(state,side){return Object.values(state.units).filter(u=>u.side===side&&u.lifeState===LIFE_STATE.ALIVE).sort((a,b)=>a.draftSlot-b.draftSlot).map(u=>createHoldDeclaration({declarationId:`D${state.roundNumber}:${u.unitId}`,roundNumber:state.roundNumber,actorId:u.unitId}));}
function attacksFor(state,side){const enemies=Object.values(state.units).filter(u=>u.side!==side&&u.lifeState===LIFE_STATE.ALIVE).sort((a,b)=>a.draftSlot-b.draftSlot);return Object.values(state.units).filter(u=>u.side===side&&u.lifeState===LIFE_STATE.ALIVE).sort((a,b)=>a.draftSlot-b.draftSlot).map((u,i)=>{const target=enemies[Math.min(i,enemies.length-1)]??enemies[0],ability=getArchetype(u.archetypeId).abilities.find(a=>a.actionKind===ACTION_KIND.BASIC_ATTACK);return createRosterAbilityDeclaration({roundNumber:state.roundNumber,actorId:u.unitId,archetypeId:u.archetypeId,abilityId:ability.id,target:{type:TARGET_TYPE.UNIT,unitId:target.unitId}});});}
async function runRound({A,B,state,declarationsA,declarationsB,requestTimeout=false}){const roundNumber=state.roundNumber;if(requestTimeout){A.send('selection_timeout_request');const ga=await A.waitFor('selection_timeout_granted',m=>m.roundNumber===roundNumber),gb=await B.waitFor('selection_timeout_granted',m=>m.roundNumber===roundNumber);assert.equal(ga.remainingBySide.A,2);assert.deepEqual(ga.remainingBySide,gb.remainingBySide);}A.send('round_declarations',{declarations:declarationsA,deadlineMetadata:{selectionMs:120000,timedOut:false}});B.send('round_declarations',{declarations:declarationsB,deadlineMetadata:{selectionMs:120000,timedOut:false}});const pa=(await A.waitFor('round_package',m=>m.package.roundNumber===roundNumber)).package,pb=(await B.waitFor('round_package',m=>m.package.roundNumber===roundNumber)).package;assert.deepEqual(pa,pb);assert.equal(pa.declarationsA.length,declarationsA.length);assert.equal(pa.declarationsB.length,declarationsB.length);const ra=simulateRosterRoundPackage({baseState:state,roundPackage:pa}),rb=simulateRosterRoundPackage({baseState:state,roundPackage:pb});assert.deepEqual(ra.digest,rb.digest);A.send('round_digest',{digest:ra.digest});B.send('round_digest',{digest:rb.digest});const ca=await A.waitFor('round_confirmed',m=>m.roundNumber===roundNumber),cb=await B.waitFor('round_confirmed',m=>m.roundNumber===roundNumber);assert.equal(ca.finalStateHash,ra.digest.finalStateHash);assert.equal(ca.eventStreamHash,ra.digest.eventStreamHash);assert.equal(cb.finalStateHash,rb.digest.finalStateHash);return{result:ra,confirmed:ca};}
async function readyNext({A,B,result,confirmed}){const payload={roundNumber:confirmed.roundNumber,finalStateHash:confirmed.finalStateHash,eventStreamHash:confirmed.eventStreamHash};A.send('round_ready',payload);B.send('round_ready',payload);const oa=await A.waitFor('round_open'),ob=await B.waitFor('round_open');assert.equal(oa.roundNumber,confirmed.roundNumber+1);assert.equal(ob.roundNumber,confirmed.roundNumber+1);advanceClosedRound(result.sim);return structuredClone(result.sim.state);}
if(typeof WebSocket!=='function'){test('Stage25D live multiplayer validation requires WebSocket client support',{skip:true},()=>{});}else{
  test('Stage25D actual two-socket operation validates planning, hashes, readiness and all five formats',async t=>{const{child,url}=await startServer();t.after(()=>{try{child.kill('SIGTERM');}catch{}});for(let n=1;n<=5;n++)await t.test(`${n}v${n}`,async()=>{const pair=await createAndDraft({url,teamSize:n,label:`LIVE${n}`});let state=createTeamBattleState({teamA:pair.started.teamA,teamB:pair.started.teamB,matchId:pair.started.matchId});const round=await runRound({A:pair.A,B:pair.B,state,declarationsA:holdsFor(state,'A'),declarationsB:holdsFor(state,'B'),requestTimeout:n===3});state=await readyNext({A:pair.A,B:pair.B,...round});assert.equal(state.roundNumber,2);if(n===5){pair.B.close();const d=await pair.A.waitFor('opponent_disconnected');assert.equal(d.during,'IN_MATCH');assert.equal((await pair.A.waitFor('room_closed')).reason,'SOCKET_CLOSED');pair.A.close();}else{pair.A.close();pair.B.close();}});});
  test('Stage25D live match completes and same-room rematch restarts after two votes',async t=>{const{child,url}=await startServer();t.after(()=>{try{child.kill('SIGTERM');}catch{}});const pair=await createAndDraft({url,teamSize:1,label:'REMATCH',pickPlan:{A:['Barbarian'],B:['Necromancer']}});assert.deepEqual(pair.started.teamA,['Barbarian']);assert.deepEqual(pair.started.teamB,['Necromancer']);let state=createTeamBattleState({teamA:pair.started.teamA,teamB:pair.started.teamB,matchId:pair.started.matchId}),completed=null;for(let i=0;i<10;i++){const round=await runRound({A:pair.A,B:pair.B,state,declarationsA:attacksFor(state,'A'),declarationsB:attacksFor(state,'B')});if(round.result.sim.state.outcome.status==='COMPLETE'){completed=round;break;}state=await readyNext({A:pair.A,B:pair.B,...round});}assert.ok(completed);const outcome=completed.result.sim.state.outcome,report={roundNumber:completed.confirmed.roundNumber,winner:outcome.winner,finalStateHash:completed.confirmed.finalStateHash,eventStreamHash:completed.confirmed.eventStreamHash};pair.A.send('match_complete',report);pair.B.send('match_complete',report);const da=await pair.A.waitFor('match_complete_confirmed'),db=await pair.B.waitFor('match_complete_confirmed');assert.equal(da.winner,outcome.winner);assert.equal(db.finalStateHash,completed.confirmed.finalStateHash);pair.A.send('request_rematch');assert.deepEqual((await pair.A.waitFor('rematch_status',m=>m.votes.length===1)).votes,['A']);pair.B.send('request_rematch');const sa=await pair.A.waitFor('rematch_start'),sb=await pair.B.waitFor('rematch_start');assert.equal(sa.config.teamSize,1);assert.equal(sb.config.teamSize,1);const dA=await pair.A.waitFor('draft_state',m=>m.state.pickIndex===0&&!m.state.complete),dB=await pair.B.waitFor('draft_state',m=>m.state.pickIndex===0&&!m.state.complete);assert.equal(dA.state.turnSide,'A');assert.deepEqual(dA.state.available,dB.state.available);pair.A.close();pair.B.close();});
  test('Stage25D live coordinator detects a deliberately mismatched client digest and halts the round',async t=>{const{child,url}=await startServer();t.after(()=>{try{child.kill('SIGTERM');}catch{}});const pair=await createAndDraft({url,teamSize:2,label:'DESYNC'});const state=createTeamBattleState({teamA:pair.started.teamA,teamB:pair.started.teamB,matchId:pair.started.matchId});pair.A.send('round_declarations',{declarations:holdsFor(state,'A'),deadlineMetadata:{selectionMs:120000,timedOut:false}});pair.B.send('round_declarations',{declarations:holdsFor(state,'B'),deadlineMetadata:{selectionMs:120000,timedOut:false}});const pkg=(await pair.A.waitFor('round_package')).package;await pair.B.waitFor('round_package');const result=simulateRosterRoundPackage({baseState:state,roundPackage:pkg});pair.A.send('round_digest',{digest:result.digest});pair.B.send('round_digest',{digest:{...result.digest,eventStreamHash:'0000000000000000000000000000000000000000000000000000000000000000'}});const da=await pair.A.waitFor('round_desync'),db=await pair.B.waitFor('round_desync');assert.ok(da.mismatches.some(x=>x.field==='eventStreamHash'));assert.deepEqual(da.mismatches,db.mismatches);pair.A.close();pair.B.close();});
}
