import test from 'node:test';
import assert from 'node:assert/strict';
import {
 ACTION_KIND, LIFE_STATE, ROSTER, ROSTER_IDS, SIDE, TARGET_TYPE,
 createBattleState, createHoldDeclaration, createRoundSimulation, createRosterAbilityDeclaration,
 createRosterCombatScheduler, createRosterUnit, getAbility, poisonTotal, validateRoster
} from '../src/index.js';

function pair(a='Warrior',b='Barbarian', apos={row:3,col:2},bpos={row:3,col:5}){
 return createBattleState({matchId:'S19',units:[createRosterUnit({archetypeId:a,unitId:'H0',side:SIDE.A,draftSlot:0,position:apos}),createRosterUnit({archetypeId:b,unitId:'G0',side:SIDE.B,draftSlot:0,position:bpos})]});
}
function hold(id){return createHoldDeclaration({declarationId:`D1:${id}`,roundNumber:1,actorId:id});}
function run(state,decs,seed=123){const sim=createRoundSimulation({state,declarations:decs,seed});createRosterCombatScheduler(sim,{countersEnabled:false}).runUntilCombatSettled({maxCycles:50});return sim;}

test('full roster contains exactly the 12 approved archetypes',()=>{assert.deepEqual([...ROSTER_IDS].sort(),['Archer','Barbarian','Cleric','Electromancer','Mage','Monk','Mystic','Necromancer','Paladin','Rogue','Shinobi','Warrior'].sort());});
test('roster validation succeeds and migrates at least 70 ability entries',()=>{const v=validateRoster();assert.equal(v.ok,true);assert.equal(v.archetypes,12);assert.ok(v.abilities>=70);});
test('each archetype has a native basic weapon profile and 5+ kit entries',()=>{for(const c of Object.values(ROSTER)){assert.ok(c.abilities.length>=5);assert.ok(c.abilities.some(a=>a.actionKind===ACTION_KIND.BASIC_ATTACK));assert.ok(c.combat.attacksMax>0);assert.ok(c.weapon.weaponRange>0);}});
test('legacy fast/normal/slow are migrated as numeric 1/3/5 starting values',()=>{assert.equal(getAbility('Mage','METEOR').completionDelayCycles,1);assert.equal(getAbility('Mystic','BERSERK').completionDelayCycles,3);assert.equal(getAbility('Mage','FIREBALL').completionDelayCycles,5);});
test('Fireball is an explicit 5x5 ground-targeted spell',()=>{const a=getAbility('Mage','FIREBALL');assert.equal(a.targetType,TARGET_TYPE.GROUND);assert.equal(a.area.shape,'SQUARE_5X5');});
test('Arcane Echo and Counterstance are now native playable rule overrides',()=>{const echo=getAbility('Mage','ARCANE_ECHO');assert.notEqual(echo.playable,false);assert.equal(echo.effects[0].key,'arcane_echo');assert.equal(echo.effects[0].duration,2);const cs=getAbility('Monk','COUNTERSTANCE');assert.notEqual(cs.playable,false);assert.equal(cs.effects[0].key,'counterstance');assert.equal(cs.effects[0].data.profile,'FREE_COUNTERS');for(const [c,id] of [['Mage','ARCANE_ECHO'],['Monk','COUNTERSTANCE']]){const d=createRosterAbilityDeclaration({roundNumber:1,actorId:'H0',archetypeId:c,abilityId:id,target:{type:TARGET_TYPE.SELF}});assert.equal(d.actionId,id);}});
test('limited-use identities migrate: God Tempest 1, Resurrection 2, Regen Potion 3',()=>{assert.equal(getAbility('Electromancer','GOD_TEMPEST').usesMax,1);assert.equal(getAbility('Cleric','RESURRECTION').usesMax,2);assert.equal(getAbility('Shinobi','REGEN_POTION').usesMax,3);});
test('Mystic uses native Throwing Dagger profile while Archer remains standard ranged',()=>{assert.equal(ROSTER.Mystic.weapon.behavior,'THROWING_DAGGER');assert.equal(ROSTER.Mystic.weapon.counterMoveMax,2);assert.equal(ROSTER.Archer.weapon.behavior,'STANDARD');assert.equal(ROSTER.Archer.weapon.mode,'RANGED');});
test('physical special attack style uses BASIC_ATTACK runtime and resolves pursuit damage',()=>{const state=pair('Monk','Barbarian',{row:3,col:3},{row:3,col:5});state.units.G0.stats.QKN=-100;const d=createRosterAbilityDeclaration({roundNumber:1,actorId:'H0',archetypeId:'Monk',abilityId:'PALM_HIT',target:{type:TARGET_TYPE.UNIT,unitId:'G0'}});assert.equal(d.actionKind,ACTION_KIND.BASIC_ATTACK);const sim=run(state,[d,hold('G0')],99);assert.ok(sim.state.units.G0.stats.hp<sim.state.units.G0.stats.maxHP);assert.equal(sim.runtimes['R1:H0'].state,'COMPLETED');});
test('Warhorn executes roster team resource buffs after its 2-cycle cast',()=>{const state=pair('Warrior','Barbarian');const beforeA=state.units.H0.resources.attacksMax,beforeM=state.units.H0.resources.movementMax;const d=createRosterAbilityDeclaration({roundNumber:1,actorId:'H0',archetypeId:'Warrior',abilityId:'WARHORN'});assert.equal(getAbility('Warrior','WARHORN').completionDelayCycles,2);const sim=run(state,[d,hold('G0')],101);assert.equal(sim.state.units.H0.resources.attacksMax,beforeA+1);assert.equal(sim.state.units.H0.resources.movementMax,beforeM+2);assert.ok(sim.state.units.H0.statuses.some(s=>s.key==='warhorn_attacks_up'));assert.ok(sim.state.units.H0.statuses.some(s=>s.key==='warhorn_movement_up'));});
test('Poison Dagger migration is now a self Poison Imbue setup spell',()=>{const state=pair('Rogue','Warrior',{row:3,col:3},{row:3,col:5});const d=createRosterAbilityDeclaration({roundNumber:1,actorId:'H0',archetypeId:'Rogue',abilityId:'POISON_DAGGER',target:{type:TARGET_TYPE.SELF}});const sim=run(state,[d,hold('G0')],1);const imbue=sim.state.units.H0.statuses.find(s=>s.key==='poison_imbue');assert.ok(imbue);assert.equal(imbue.duration,3);assert.equal(poisonTotal(sim.state.units.G0),0);});
test('Regen Potion is an ITEM, spends one of three uses, heals 35–60% max HP, and cures poison',()=>{const state=pair('Shinobi','Warrior');state.units.H0.stats.hp=Math.max(1,state.units.H0.stats.maxHP-900);state.units.H0.statuses.push({key:'poison',duration:null,sourceId:'G0',data:{contributions:[{amount:50,sourceId:'G0'}]}});const before=state.units.H0.stats.hp,maxHP=state.units.H0.stats.maxHP;const d=createRosterAbilityDeclaration({roundNumber:1,actorId:'H0',archetypeId:'Shinobi',abilityId:'REGEN_POTION'});assert.equal(d.actionKind,ACTION_KIND.ITEM);const sim=run(state,[d,hold('G0')],22);const healed=sim.state.units.H0.stats.hp-before;assert.equal(sim.state.units.H0.limitedUses.potion_regen,2);assert.equal(poisonTotal(sim.state.units.H0),0);assert.ok(healed>=Math.floor(maxHP*.35)&&healed<=Math.floor(maxHP*.60));});
test('Resurrection revives an allied corpse on its occupied square and spends one resurrection charge',()=>{const cleric=createRosterUnit({archetypeId:'Cleric',unitId:'H0',side:SIDE.A,draftSlot:0,position:{row:3,col:2}});const ally=createRosterUnit({archetypeId:'Warrior',unitId:'H1',side:SIDE.A,draftSlot:1,position:{row:3,col:4}});const enemy=createRosterUnit({archetypeId:'Barbarian',unitId:'G0',side:SIDE.B,draftSlot:0,position:{row:3,col:8}});ally.stats.hp=0;ally.lifeState=LIFE_STATE.DEAD;const state=createBattleState({matchId:'S19-RES',units:[cleric,ally,enemy]});const d=createRosterAbilityDeclaration({roundNumber:1,actorId:'H0',archetypeId:'Cleric',abilityId:'RESURRECTION',target:{type:TARGET_TYPE.UNIT,unitId:'H1'}});const sim=createRoundSimulation({state,declarations:[d,hold('G0')],seed:55});createRosterCombatScheduler(sim,{countersEnabled:false}).runUntilCombatSettled({maxCycles:20});assert.equal(sim.state.units.H1.lifeState,LIFE_STATE.ALIVE);assert.ok(sim.state.units.H1.stats.hp>0);assert.equal(sim.state.board.occupancy['3,4'],'H1');assert.equal(sim.state.units.H0.limitedUses.resurrection,1);});
test('Fireball roster execution damages a live occupant inside the locked 5x5 area',()=>{const state=pair('Mage','Warrior',{row:3,col:1},{row:5,col:8});const d=createRosterAbilityDeclaration({roundNumber:1,actorId:'H0',archetypeId:'Mage',abilityId:'FIREBALL',target:{type:TARGET_TYPE.GROUND,row:5,col:8}});const sim=run(state,[d,hold('G0')],77);assert.ok(sim.state.units.G0.stats.hp<sim.state.units.G0.stats.maxHP);});
test('God Tempest consumes its only use, full-heals, cleanses negatives, and buffs SDM/DEF',()=>{const state=pair('Electromancer','Warrior');const u=state.units.H0;u.stats.hp=100;u.statuses.push({key:'def_down',duration:3,sourceId:'G0',data:{}},{key:'marked',duration:2,sourceId:'G0',data:{}});const d=createRosterAbilityDeclaration({roundNumber:1,actorId:'H0',archetypeId:'Electromancer',abilityId:'GOD_TEMPEST'});const sim=run(state,[d,hold('G0')],88);const out=sim.state.units.H0;assert.equal(out.stats.hp,out.stats.maxHP);assert.equal(out.limitedUses.god_tempest,0);assert.ok(!out.statuses.some(s=>s.key==='def_down'||s.key==='marked'));assert.ok(out.statuses.some(s=>s.key==='sdm_up'));assert.ok(out.statuses.some(s=>s.key==='def_up'));});

test('every playable migrated ability compiles into canonical declaration data',()=>{for(const [cid,c] of Object.entries(ROSTER)){for(const a of c.abilities){if(a.playable===false)continue;let target;if(a.targetType===TARGET_TYPE.UNIT)target={type:TARGET_TYPE.UNIT,unitId:'G0'};else if(a.targetType===TARGET_TYPE.GROUND)target={type:TARGET_TYPE.GROUND,row:5,col:5};const d=createRosterAbilityDeclaration({roundNumber:1,actorId:'H0',archetypeId:cid,abilityId:a.id,target});assert.equal(d.actionId,a.id);}}});
test('same roster action package and seed replay deterministically',()=>{const state1=pair('Necromancer','Warrior'),state2=pair('Necromancer','Warrior');const d1=createRosterAbilityDeclaration({roundNumber:1,actorId:'H0',archetypeId:'Necromancer',abilityId:'POISON_BOLT',target:{type:TARGET_TYPE.UNIT,unitId:'G0'}});const d2=hold('G0');const a=run(state1,[d1,d2],0xdeadbeef),b=run(state2,[d2,d1],0xdeadbeef);assert.deepEqual(a.state,b.state);assert.deepEqual(a.events.snapshot(),b.events.snapshot());assert.equal(a.rng.drawCount,b.rng.drawCount);assert.equal(a.rng.state,b.rng.state);});
