export const PROTOCOL_VERSION = 2;
export const RULESET_VERSION = 'ros2-direct-stats-2.2';

export const SIDE = Object.freeze({
  A: 'A',
  B: 'B'
});

export const LIFE_STATE = Object.freeze({
  ALIVE: 'ALIVE',
  DEAD: 'DEAD'
});

export const ACTION_KIND = Object.freeze({
  BASIC_ATTACK: 'BASIC_ATTACK',
  ABILITY: 'ABILITY',
  SPELL: 'SPELL',
  ITEM: 'ITEM',
  HOLD: 'HOLD'
});

export const TARGET_TYPE = Object.freeze({
  NONE: 'NONE',
  UNIT: 'UNIT',
  GROUND: 'GROUND',
  SELF: 'SELF',
  TEAM: 'TEAM',
  ALL_ENEMIES: 'ALL_ENEMIES',
  ALL_ALLIES: 'ALL_ALLIES'
});

export const DAMAGE_TYPE = Object.freeze({
  PHYSICAL: 'PHYSICAL',
  MAGICAL: 'MAGICAL'
});

export const WEAPON_BEHAVIOR = Object.freeze({
  STANDARD: 'STANDARD',
  THROWING_DAGGER: 'THROWING_DAGGER'
});

export const RETARGET_POLICY = Object.freeze({
  IN_RANGE_NEAREST: 'IN_RANGE_NEAREST',
  IN_RANGE_RANDOM: 'IN_RANGE_RANDOM'
});


export const ACTION_RUNTIME_STATE = Object.freeze({
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  CHARGING: 'CHARGING',
  COMPLETED: 'COMPLETED',
  INTERRUPTED: 'INTERRUPTED',
  IMPOSSIBLE: 'IMPOSSIBLE'
});

export const EVENT_TYPE = Object.freeze({
  ROUND_START: 'ROUND_START',
  ROUND_END: 'ROUND_END',
  ACTION_START: 'ACTION_START',
  ACTION_COMPLETE: 'ACTION_COMPLETE',
  ACTION_INTERRUPT: 'ACTION_INTERRUPT',
  MOVE: 'MOVE',
  ATTACK_START: 'ATTACK_START',
  ATTACK_IMPACT: 'ATTACK_IMPACT',
  COUNTER_MOVE: 'COUNTER_MOVE',
  COUNTER: 'COUNTER',
  CAST_START: 'CAST_START',
  CAST_INTERRUPT: 'CAST_INTERRUPT',
  CAST_COMPLETE: 'CAST_COMPLETE',
  CAST_FIZZLE: 'CAST_FIZZLE',
  STUN: 'STUN',
  SILENCE: 'SILENCE',
  TAUNT: 'TAUNT',
  BERSERK: 'BERSERK',
  ITEM_START: 'ITEM_START',
  ITEM_INTERRUPT: 'ITEM_INTERRUPT',
  ITEM_COMPLETE: 'ITEM_COMPLETE',
  DAMAGE: 'DAMAGE',
  HEAL: 'HEAL',
  MISS: 'MISS',
  DODGE: 'DODGE',
  BLOCK: 'BLOCK',
  CRIT: 'CRIT',
  STATUS_APPLY: 'STATUS_APPLY',
  STATUS_TICK: 'STATUS_TICK',
  STATUS_DURATION: 'STATUS_DURATION',
  STATUS_REMOVE: 'STATUS_REMOVE',
  STATUS_EXPIRE: 'STATUS_EXPIRE',
  PUSH: 'PUSH',
  PULL: 'PULL',
  TELEPORT: 'TELEPORT',
  INTERCEPT: 'INTERCEPT',
  SPELL_RESOLUTION: 'SPELL_RESOLUTION',
  KO: 'KO',
  RESURRECT: 'RESURRECT',
  SUMMON: 'SUMMON'
});
