import { ACTION_KIND, ACTION_RUNTIME_STATE, EVENT_TYPE, LIFE_STATE, TARGET_TYPE } from './constants.js';
import { invariant } from './errors.js';
import { isInBounds, manhattanDistance } from './grid.js';
import { getAbility } from './roster.js';
import { resolveRosterEffects } from './roster-effects.js';
import { hasStatus } from './status.js';
import { effectiveCompletionDelay } from './rule-overrides.js';

const supported=new Set([ACTION_KIND.ABILITY,ACTION_KIND.ITEM]);
function sync(sim){sim.state.round.eventSequence=sim.events.length;}
function emit(sim,type,opts){const e=sim.events.emit(type,opts);sync(sim);return e;}
function decl(sim,r){return sim.declarations.find(d=>d.declarationId===r.declarationId);}
function terminal(r){return [ACTION_RUNTIME_STATE.COMPLETED,ACTION_RUNTIME_STATE.INTERRUPTED,ACTION_RUNTIME_STATE.IMPOSSIBLE].includes(r.state);}
function spec(sim,r){const d=decl(sim,r);const ref=d.payload?.roster;invariant(ref,'Roster action requires payload.roster');return {d,ability:getAbility(ref.archetypeId,ref.abilityId),action:d.payload.action};}
function validity(sim,r,ability,d){const actor=sim.state.units[r.actorId];if(!actor||actor.lifeState!==LIFE_STATE.ALIVE)return {valid:false,reason:'ACTOR_DEAD'};let target=null,ground=null;
 if(d.target.type===TARGET_TYPE.UNIT){target=sim.state.units[d.target.unitId];if(!target)return {valid:false,reason:'TARGET_MISSING'};if(ability.deadTargetOnly===true){if(target.lifeState!==LIFE_STATE.DEAD||target.side!==actor.side)return {valid:false,reason:'TARGET_MUST_BE_KO_ALLY'};}else if(target.lifeState===LIFE_STATE.DEAD&&!ability.allowDeadTarget)return {valid:false,reason:'TARGET_DEAD'};if(manhattanDistance(actor.position,target.position)>ability.castRange)return {valid:false,reason:'OUT_OF_RANGE'};}
 if(d.target.type===TARGET_TYPE.GROUND){ground={row:d.target.row,col:d.target.col};if(!isInBounds(sim.state.board,ground.row,ground.col))return {valid:false,reason:'GROUND_OUT_OF_BOUNDS'};if(manhattanDistance(actor.position,ground)>ability.castRange)return {valid:false,reason:'OUT_OF_RANGE'};}
 if(d.target.type===TARGET_TYPE.SELF)target=actor; return {valid:true,target,ground};}
function spendUse(actor,ability){if(!ability.usesMax)return true;const key=ability.usesKey??ability.id;const left=actor.limitedUses[key]??ability.usesMax;if(left<=0)return false;actor.limitedUses[key]=left-1;return true;}
export function startPendingRosterActions(sim,cycle){const out=[];for(const r of Object.values(sim.runtimes).filter(r=>supported.has(r.actionKind)&&r.state===ACTION_RUNTIME_STATE.PENDING).sort((a,b)=>a.actorId.localeCompare(b.actorId))){const actor=sim.state.units[r.actorId];if(!actor||actor.lifeState!==LIFE_STATE.ALIVE){r.state=ACTION_RUNTIME_STATE.INTERRUPTED;r.interrupted=true;continue;}const {ability,action}=spec(sim,r);const blockReason=ability.hardControlBypass===true?null:(hasStatus(actor,'stun')?'STUN':(ability.silenceSensitive===true&&hasStatus(actor,'silence')?'SILENCE':null));if(blockReason){r.state=ACTION_RUNTIME_STATE.INTERRUPTED;r.interrupted=true;r.metadata.interruptReason=blockReason;emit(sim,EVENT_TYPE.ACTION_INTERRUPT,{initiativeCycle:cycle,actorId:r.actorId,targetId:r.declaredPrimaryTargetId,payload:{reason:blockReason,actionId:ability.id,preventedStart:true}});continue;}if(!spendUse(actor,ability)){r.state=ACTION_RUNTIME_STATE.IMPOSSIBLE;emit(sim,EVENT_TYPE.ACTION_INTERRUPT,{initiativeCycle:cycle,actorId:r.actorId,targetId:r.declaredPrimaryTargetId,payload:{reason:'NO_USES',abilityId:ability.id}});continue;}const effectiveDelay=effectiveCompletionDelay(actor,action.completionDelayCycles);r.state=ACTION_RUNTIME_STATE.CHARGING;r.castStartCycle=cycle;r.completionCycle=cycle+effectiveDelay;r.metadata.baseCompletionDelayCycles=action.completionDelayCycles;r.metadata.completionDelayCycles=effectiveDelay;const start=emit(sim,EVENT_TYPE.ACTION_START,{initiativeCycle:cycle,actorId:r.actorId,targetId:r.declaredPrimaryTargetId,payload:{actionId:ability.id,actionKind:r.actionKind,completionCycle:r.completionCycle,baseCompletionDelayCycles:action.completionDelayCycles,completionDelayCycles:effectiveDelay,premonitionApplied:effectiveDelay!==action.completionDelayCycles,groundLock:r.groundLock?{...r.groundLock}:null,actorPositionAtStart:actor.position?{...actor.position}:null}});if(r.actionKind===ACTION_KIND.ITEM)emit(sim,EVENT_TYPE.ITEM_START,{initiativeCycle:cycle,actorId:r.actorId,targetId:r.declaredPrimaryTargetId,parentEventId:start.eventId,payload:{actionId:ability.id,completionCycle:r.completionCycle}});out.push(r.actorId);}return out;}
export function resolveMaturedRosterActions(sim,cycle){const rs=Object.values(sim.runtimes).filter(r=>supported.has(r.actionKind)&&r.state===ACTION_RUNTIME_STATE.CHARGING&&r.completionCycle<=cycle).sort((a,b)=>{const qa=sim.state.units[a.actorId]?.stats.QKN??0,qb=sim.state.units[b.actorId]?.stats.QKN??0;return qb-qa||a.actorId.localeCompare(b.actorId);});const out=[];for(const r of rs){const {d,ability}=spec(sim,r);const v=validity(sim,r,ability,d);if(!v.valid){r.state=ACTION_RUNTIME_STATE.IMPOSSIBLE;emit(sim,EVENT_TYPE.ACTION_INTERRUPT,{initiativeCycle:cycle,actorId:r.actorId,targetId:r.declaredPrimaryTargetId,payload:{reason:v.reason,abilityId:ability.id}});out.push({actorId:r.actorId,result:'FIZZLE'});continue;}const doneType=r.actionKind===ACTION_KIND.ITEM?EVENT_TYPE.ITEM_COMPLETE:EVENT_TYPE.ACTION_COMPLETE;const done=emit(sim,doneType,{initiativeCycle:cycle,actorId:r.actorId,targetId:r.declaredPrimaryTargetId,payload:{actionId:ability.id,actionKind:r.actionKind,groundLock:r.groundLock?{...r.groundLock}:null,actorPositionAtCompletion:sim.state.units[r.actorId]?.position?{...sim.state.units[r.actorId].position}:null,targetPositionAtCompletion:v.target?.position?{...v.target.position}:v.ground?{...v.ground}:null}});const effects=resolveRosterEffects(sim,{actorId:r.actorId,ability,validity:v,cycle,parentEventId:done.eventId});r.state=ACTION_RUNTIME_STATE.COMPLETED;r.completed=true;out.push({actorId:r.actorId,result:'COMPLETE',abilityId:ability.id,effects});}return out;}
export function getNonTerminalRosterActions(sim){return Object.values(sim.runtimes).filter(r=>supported.has(r.actionKind)&&!terminal(r));}
