import { DAMAGE_TYPE, EVENT_TYPE, LIFE_STATE } from './constants.js';
import { AREA_SHAPE, unitsInArea } from './area.js';
import { applyDamageMitigation, getPhysicalDodgeChance } from './combat.js';
import { applyControlEffect, expireControlEffect, CONTROL_TYPE } from './controls.js';
import { markUnitDead } from './grid.js';
import { applyBleed, applyPoison, applyTimedStatus, poisonTotal, STATUS_STACK } from './status-engine.js';
import { findStatus, removeStatus, statusKey } from './status.js';
import { effectiveStat, incomingDamageMultiplier } from './modifiers.js';
import { blindWhiffChance, consumePhysicalAttackBreakingInvisibility, effectiveCritMultiplier, resolvePostMeleeHitOverrides, resolveShieldwallIntercept, stripOneDefensiveBuff } from './rule-overrides.js';
import { summonFaery } from './summons.js';

const CONTROL = new Set(['stun','silence','taunt','berserk']);
const NEGATIVE = new Set(['stun','silence','taunt','berserk','root','suppression','spellbreak','poison','bleed','def_down','rend_def_down','atk_down','sdm_down','marked','blind']);
const BENEFICIAL = new Set(['atk_up','sdm_up','def_up','guard','magic_shield','divine_shield','physical_shield','shield_redirect','shinobi_haste','invisible','premonition','arcane_echo','regen','shift','bloodlust','counterstance','flurry_style','poison_imbue','bleed_imbue','shadowstep_crit','ward','unstoppable','detection','warhorn_attacks_up','warhorn_movement_up']);
function sync(sim){sim.state.round.eventSequence=sim.events.length;}
function emit(sim,type,opts){const e=sim.events.emit(type,opts);sync(sim);return e;}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function unitsCanonical(sim){return Object.values(sim.state.units).sort((a,b)=>a.unitId.localeCompare(b.unitId));}
function updateBattleOutcome(state){const livingA=Object.values(state.units).some(u=>u.side==='A'&&u.lifeState===LIFE_STATE.ALIVE&&u.entityKind!=='SUMMON'),livingB=Object.values(state.units).some(u=>u.side==='B'&&u.lifeState===LIFE_STATE.ALIVE&&u.entityKind!=='SUMMON');if(livingA&&livingB)return;state.outcome.status='COMPLETE';state.outcome.winner=livingA?'A':(livingB?'B':null);}
function rollRange(sim,min,max,reason){min=Math.trunc(min??0);max=Math.trunc(max??min);return min===max?min:sim.rng.nextInt(min,max,reason);}
function targetsFor(sim,actor,effect,validity){
 const scope=effect.to??effect.scope??'TARGET';
 if(scope==='SELF') return [actor];
 if(scope==='ALL_ALLIES') return unitsCanonical(sim).filter(u=>u.side===actor.side&&u.lifeState===LIFE_STATE.ALIVE);
 if(scope==='ALL_ENEMIES') return unitsCanonical(sim).filter(u=>u.side!==actor.side&&u.lifeState===LIFE_STATE.ALIVE);
 if(scope==='TARGET') return validity.target?[validity.target]:[];
 return validity.target?[validity.target]:[];
}
function applyDamage(sim,actor,target,spec,cycle,parentEventId,label){
 if(!target||target.lifeState!==LIFE_STATE.ALIVE)return {dealt:0,killed:false,dodged:false,targetId:target?.unitId??null};
 const intendedTarget=target;
 const damageType=spec.damageType??DAMAGE_TYPE.PHYSICAL;
 const stealthContext = damageType===DAMAGE_TYPE.PHYSICAL
   ? consumePhysicalAttackBreakingInvisibility(sim, actor.unitId, { cycle, parentEventId, reason:`ABILITY:${label}` })
   : { wasInvisible:false, consumed:false };
 if(damageType===DAMAGE_TYPE.PHYSICAL && spec.dodgeable!==false){
   const blind=blindWhiffChance(actor);if(blind>0&&sim.rng.chance(blind,`ABILITY_BLIND_WHIF:${label}:${actor.unitId}->${target.unitId}`)){emit(sim,EVENT_TYPE.MISS,{initiativeCycle:cycle,actorId:actor.unitId,targetId:target.unitId,parentEventId,payload:{source:'ABILITY',abilityId:label,reason:'BLIND'}});return {dealt:0,killed:false,dodged:false,missed:true,targetId:target.unitId};}
   const p=getPhysicalDodgeChance(target); if(p>0&&sim.rng.chance(p,`ABILITY_DODGE:${label}:${target.unitId}<-${actor.unitId}`)){ emit(sim,EVENT_TYPE.DODGE,{initiativeCycle:cycle,actorId:actor.unitId,targetId:target.unitId,parentEventId,payload:{source:'ABILITY',abilityId:label,dodgeChance:p}}); return {dealt:0,killed:false,dodged:true,targetId:target.unitId}; }
 }
 const intercept=(damageType===DAMAGE_TYPE.PHYSICAL)?resolveShieldwallIntercept(sim,actor.unitId,target.unitId,{cycle,parentEventId}):{targetId:target.unitId,intercepted:false};
 target=sim.state.units[intercept.targetId]??target;
 const selectedWeaponMultiplier = stealthContext.wasInvisible && Number.isFinite(spec.stealthWeaponMultiplier) ? spec.stealthWeaponMultiplier : spec.weaponMultiplier;
 const base=Number.isFinite(selectedWeaponMultiplier)?Math.max(1,Math.floor(rollRange(sim,actor.weapon.attackBaseMin,actor.weapon.attackBaseMax,`ABILITY_WEAPON_DAMAGE:${label}:${actor.unitId}`)*(selectedWeaponMultiplier??1))):rollRange(sim,spec.min,spec.max,`ABILITY_DAMAGE:${label}:${actor.unitId}`);
 const scale=effectiveStat(actor,spec.scalesWith??(damageType===DAMAGE_TYPE.MAGICAL?'SDM':'ATK'));
 let raw=Math.max(0,Math.floor(base*Math.max(0,scale)/100));
 const critP=clamp((actor.stats.CRIT??0)+(spec.critBonus??0)+(stealthContext.wasInvisible?(spec.stealthCritBonus??0):0),0,1); let crit=false;
 const critMult=effectiveCritMultiplier(actor,Number.isFinite(spec.critMultiplier)?spec.critMultiplier:null);
 if(critP>=1|| (critP>0&&sim.rng.chance(critP,`ABILITY_CRIT:${label}:${actor.unitId}->${target.unitId}`))){crit=true;raw=Math.floor(raw*critMult);emit(sim,EVENT_TYPE.CRIT,{initiativeCycle:cycle,actorId:actor.unitId,targetId:target.unitId,parentEventId:intercept.eventId??parentEventId,payload:{source:'ABILITY',abilityId:label,multiplier:critMult}});}
 let amount=applyDamageMitigation(raw,target,damageType,spec.defensePenetration??0);
 const preIncomingDamage=amount;
 const incomingMultiplier=incomingDamageMultiplier(target,damageType);
 amount=Math.max(0,Math.floor(amount*incomingMultiplier));
 const before=target.stats.hp; target.stats.hp=Math.max(0,before-amount); const dealt=before-target.stats.hp;
 const damage=emit(sim,EVENT_TYPE.DAMAGE,{initiativeCycle:cycle,actorId:actor.unitId,targetId:target.unitId,parentEventId:intercept.eventId??parentEventId,payload:{amount:dealt,hpBefore:before,hpAfter:target.stats.hp,source:'ABILITY',abilityId:label,damageType,crit,intendedTargetId:intendedTarget.unitId,intercepted:intercept.intercepted,preIncomingDamage,incomingDamageMultiplier:incomingMultiplier,mitigated:Math.max(0,preIncomingDamage-dealt),...(spec.simultaneousGroup?{simultaneousGroup:spec.simultaneousGroup}:{})}});
 let killed=false; if(target.stats.hp<=0&&target.lifeState===LIFE_STATE.ALIVE){markUnitDead(sim.state,target.unitId);updateBattleOutcome(sim.state);killed=true;emit(sim,EVENT_TYPE.KO,{initiativeCycle:cycle,actorId:actor.unitId,targetId:target.unitId,parentEventId:damage.eventId,payload:{position:target.position,source:'ABILITY',abilityId:label}});}
 if(!killed)resolvePostMeleeHitOverrides(sim,{attackerId:actor.unitId,defenderId:target.unitId,dealt,cycle,parentEventId:damage.eventId,source:'ABILITY'});
 return {dealt,killed,dodged:false,damageEventId:damage.eventId,targetId:target.unitId,intendedTargetId:intendedTarget.unitId,crit,stealthContext};
}
function healTarget(sim,actor,target,spec,cycle,parentEventId,label){
 if(!target||target.lifeState!==LIFE_STATE.ALIVE)return 0; let amount;
 if(Number.isFinite(spec.fixedAmount)) amount=Math.max(0,Math.floor(spec.fixedAmount));
 else if(Number.isFinite(spec.pctMaxHP)) amount=Math.floor(target.stats.maxHP*spec.pctMaxHP);
 else {const base=rollRange(sim,spec.min,spec.max,`ABILITY_HEAL:${label}:${actor.unitId}`); amount=Math.max(0,Math.floor(base*Math.max(0,effectiveStat(actor,spec.scalesWith??'SDM'))/100));}
 const before=target.stats.hp;target.stats.hp=Math.min(target.stats.maxHP,before+amount);const healed=target.stats.hp-before;emit(sim,EVENT_TYPE.HEAL,{initiativeCycle:cycle,actorId:actor.unitId,targetId:target.unitId,parentEventId,payload:{amount:healed,hpBefore:before,hpAfter:target.stats.hp,source:'ABILITY',abilityId:label,...(spec.simultaneousGroup?{simultaneousGroup:spec.simultaneousGroup}:{})}});return healed;
}
function applyStatus(sim,actor,target,effect,cycle,parentEventId){
 if(!target||target.lifeState!==LIFE_STATE.ALIVE)return false; const chance=effect.chance??1;if(chance<1&&!sim.rng.chance(chance,`STATUS_CHANCE:${effect.key}:${actor.unitId}->${target.unitId}`)){if(effect.data?.announceResist){emit(sim,EVENT_TYPE.BLOCK,{initiativeCycle:cycle,actorId:target.unitId,targetId:target.unitId,parentEventId,payload:{reason:'STATUS_RESIST',blockedStatusKey:statusKey(effect.key),hostileSourceId:actor.unitId}});}return false;}
 const key=statusKey(effect.key); if(CONTROL.has(key)){applyControlEffect(sim,target.unitId,{type:key.toUpperCase(),sourceId:actor.unitId,duration:effect.duration,cycle,parentEventId});return true;}
 if(effect.stackMode==='STACK'){const existing=findStatus(target,key);const stacks=Math.min(5,(existing?.data?.stacks??0)+1);return Boolean(applyTimedStatus(sim,target.unitId,{key,duration:effect.duration,sourceId:actor.unitId,data:{...(effect.data??{}),stacks},stack:STATUS_STACK.REFRESH,cycle,parentEventId}));}
 return Boolean(applyTimedStatus(sim,target.unitId,{key,duration:effect.duration,sourceId:actor.unitId,data:effect.data??{},stack:effect.stackMode==='MAX_DURATION'?STATUS_STACK.MAX_DURATION:STATUS_STACK.REFRESH,cycle,parentEventId}));
}
function cleanseOne(sim,actor,target,effect,cycle,parentEventId,abilityId=null){
 const before=[...target.statuses]; let removeKeys;
 if(Array.isArray(effect.keys)) removeKeys=new Set(effect.keys.map(statusKey));
 else if(effect.mode==='NEGATIVE') removeKeys=NEGATIVE;
 else if(effect.mode==='NEGATIVE_AND_BLEED'||effect.mode==='CC_AND_DEBUFFS') removeKeys=NEGATIVE;
 else removeKeys=NEGATIVE;
 let n=0; for(const s of before){if(removeKeys.has(s.key)){if(s.key==='taunt'||s.key==='berserk'){expireControlEffect(sim,target.unitId,s.key.toUpperCase(),{cycle,reason:'CLEANSE',parentEventId});}else{removeStatus(target,s.key);emit(sim,EVENT_TYPE.STATUS_REMOVE,{initiativeCycle:cycle,actorId:actor.unitId,targetId:target.unitId,parentEventId,payload:{key:s.key,reason:'CLEANSE',...(abilityId?{abilityId}:{})}});}n++;}} return n;
}
function stripBeneficial(sim,actor,target,count,cycle,parentEventId){let n=0;for(const s of [...target.statuses].sort((a,b)=>a.key.localeCompare(b.key))){if(n>=count)break;if(BENEFICIAL.has(s.key)){removeStatus(target,s.key);n++;emit(sim,EVENT_TYPE.STATUS_REMOVE,{initiativeCycle:cycle,actorId:actor.unitId,targetId:target.unitId,parentEventId,payload:{key:s.key,reason:'STRIP_BENEFICIAL'}});}}return n;}

export function resolveRosterEffects(sim,{actorId,ability,effects=ability.effects,validity,cycle=sim.state.round.initiativeCycle,parentEventId=null,damageMultiplier=1}){
 const actor=sim.state.units[actorId]; const results=[]; let lastDamage=null;
 const damageScale=Math.max(0,Number(damageMultiplier??1));
 const scaledDamageEffect=(effect)=>damageScale===1?effect:{...effect,min:Number.isFinite(effect.min)?effect.min*damageScale:effect.min,max:Number.isFinite(effect.max)?effect.max*damageScale:effect.max,weaponMultiplier:Number.isFinite(effect.weaponMultiplier)?effect.weaponMultiplier*damageScale:effect.weaponMultiplier};
 for(const effect of effects){
  if(effect.type==='DAMAGE'){const ts=targetsFor(sim,actor,effect,validity);const group=ts.length>1?`${parentEventId??'ROOT'}:${ability.id}:DAMAGE`:null;for(const t of ts){lastDamage=applyDamage(sim,actor,t,{...scaledDamageEffect(effect),...(group?{simultaneousGroup:group}:{})},cycle,parentEventId,ability.id);results.push(lastDamage);}continue;}
  if(effect.type==='BACKSTAB_STRIKE'){lastDamage=applyDamage(sim,actor,validity.target,{...scaledDamageEffect(effect),damageType:DAMAGE_TYPE.PHYSICAL,dodgeable:true},cycle,parentEventId,ability.id);results.push({...lastDamage,backstab:true});continue;}
  if(effect.type==='CONDITIONAL_DAMAGE'){const afflicted=validity.target?.statuses?.some(s=>NEGATIVE.has(s.key));lastDamage=applyDamage(sim,actor,validity.target,{...scaledDamageEffect(effect)},cycle,parentEventId,ability.id);if(afflicted&&lastDamage?.dealt>0&&validity.target?.lifeState===LIFE_STATE.ALIVE){const bonus=Math.floor(lastDamage.dealt*((effect.afflictedMultiplier??1)-1));if(bonus>0){const t=validity.target,b=t.stats.hp;t.stats.hp=Math.max(0,b-bonus);const bonusDamage=emit(sim,EVENT_TYPE.DAMAGE,{initiativeCycle:cycle,actorId:actor.unitId,targetId:t.unitId,parentEventId,payload:{amount:b-t.stats.hp,hpBefore:b,hpAfter:t.stats.hp,source:'ABILITY_BONUS',abilityId:ability.id,damageType:effect.damageType??DAMAGE_TYPE.MAGICAL}});if(t.stats.hp<=0&&t.lifeState===LIFE_STATE.ALIVE){markUnitDead(sim.state,t.unitId);updateBattleOutcome(sim.state);emit(sim,EVENT_TYPE.KO,{initiativeCycle:cycle,actorId:actor.unitId,targetId:t.unitId,parentEventId:bonusDamage.eventId,payload:{position:t.position,source:'ABILITY_BONUS',abilityId:ability.id}});lastDamage={...lastDamage,killed:true};}}}results.push(lastDamage);continue;}
  if(effect.type==='HEAL'){const ts=targetsFor(sim,actor,effect,validity);const group=ts.length>1?`${parentEventId??'ROOT'}:${ability.id}:HEAL`:null;for(const t of ts)results.push({healed:healTarget(sim,actor,t,{...effect,...(group?{simultaneousGroup:group}:{})},cycle,parentEventId,ability.id)});continue;}
  if(effect.type==='HEAL_PERCENT_ROLL'){const pct=effect.minPct===effect.maxPct?effect.minPct:(effect.minPct+(effect.maxPct-effect.minPct)*sim.rng.nextFloat(`HEAL_PERCENT:${ability.id}:${actor.unitId}`));const ts=targetsFor(sim,actor,effect,validity);const group=ts.length>1?`${parentEventId??'ROOT'}:${ability.id}:HEAL`:null;for(const t of ts)results.push({healed:healTarget(sim,actor,t,{pctMaxHP:pct,...(group?{simultaneousGroup:group}:{})},cycle,parentEventId,ability.id)});continue;}
  if(effect.type==='FULL_HEAL'){const ts=targetsFor(sim,actor,effect,validity);const group=ts.length>1?`${parentEventId??'ROOT'}:${ability.id}:HEAL`:null;for(const t of ts)results.push({healed:healTarget(sim,actor,t,{pctMaxHP:1,...(group?{simultaneousGroup:group}:{})},cycle,parentEventId,ability.id)});continue;}
  if(effect.type==='APPLY_STATUS'){for(const t of targetsFor(sim,actor,effect,validity))results.push({status:effect.key,applied:applyStatus(sim,actor,t,effect,cycle,parentEventId)});continue;}
  if(effect.type==='POISON_FROM_LAST_DAMAGE'){if(lastDamage?.dealt>0&&!lastDamage.dodged){const t=sim.state.units[lastDamage.targetId];if(t?.lifeState===LIFE_STATE.ALIVE)applyPoison(sim,t.unitId,Math.max(1,Math.floor(lastDamage.dealt*(effect.ratio??1))),{sourceId:actor.unitId,cycle,parentEventId,abilityId:ability.id});}continue;}
  if(effect.type==='BLEED_ON_LAST_DAMAGE'){if(lastDamage?.dealt>0&&!lastDamage.dodged){const t=sim.state.units[lastDamage.targetId];if(t?.lifeState===LIFE_STATE.ALIVE)applyBleed(sim,t.unitId,{duration:effect.duration,pct:effect.pct,sourceId:actor.unitId,cycle,parentEventId});}continue;}
  if(effect.type==='CLEANSE'){for(const t of targetsFor(sim,actor,{to:effect.scope==='ALL_ALLIES'?'ALL_ALLIES':effect.scope==='SELF'?'SELF':'TARGET'},validity))results.push({cleansed:cleanseOne(sim,actor,t,effect,cycle,parentEventId,ability.id)});continue;}
  if(effect.type==='DISPEL_EXCEPT'){const t=validity.target;if(t){const keep=new Set(effect.keep.map(statusKey));let n=0;for(const s of [...t.statuses])if(!keep.has(s.key)){removeStatus(t,s.key);n++;emit(sim,EVENT_TYPE.STATUS_REMOVE,{initiativeCycle:cycle,actorId:actor.unitId,targetId:t.unitId,parentEventId,payload:{key:s.key,reason:'DISPEL',abilityId:ability.id}});}results.push({dispelled:n});}continue;}
  if(effect.type==='REMOVE_STATUS'){const t=validity.target;if(t){const removed=removeStatus(t,effect.key);if(removed){emit(sim,EVENT_TYPE.STATUS_REMOVE,{initiativeCycle:cycle,actorId:actor.unitId,targetId:t.unitId,parentEventId,payload:{key:statusKey(effect.key),reason:effect.reason??ability.id}});results.push({removedStatus:statusKey(effect.key)});}}continue;}
  if(effect.type==='AOE_REMOVE_STATUS'){const center=validity.ground??validity.target?.position??actor.position;const area={...(ability.area??{shape:AREA_SHAPE.SQUARE_3X3}),center};for(const t of unitsInArea(sim.state,actor.unitId,area)){if(effect.hostileOnly===true&&t.side===actor.side)continue;if(effect.friendlyOnly===true&&t.side!==actor.side)continue;const removed=removeStatus(t,effect.key);if(removed){emit(sim,EVENT_TYPE.STATUS_REMOVE,{initiativeCycle:cycle,actorId:actor.unitId,targetId:t.unitId,parentEventId,payload:{key:statusKey(effect.key),reason:effect.reason??ability.id,abilityId:ability.id}});results.push({removedStatus:statusKey(effect.key),targetId:t.unitId});}}continue;}
  if(effect.type==='STRIP_DEFENSIVE_BUFF'){if(validity.target)results.push({stripped:Boolean(stripOneDefensiveBuff(sim,actor.unitId,validity.target.unitId,{cycle,parentEventId}))});continue;}
  if(effect.type==='WEAPON_STRIKE'){lastDamage=applyDamage(sim,actor,validity.target,{weaponMultiplier:(effect.multiplier??1)*damageScale,min:actor.weapon.attackBaseMin,max:actor.weapon.attackBaseMax,scalesWith:'ATK',damageType:DAMAGE_TYPE.PHYSICAL,dodgeable:true},cycle,parentEventId,ability.id);results.push(lastDamage);continue;}
  if(effect.type==='STRIP_BENEFICIAL'){if(validity.target)results.push({stripped:stripBeneficial(sim,actor,validity.target,effect.count??1,cycle,parentEventId)});continue;}
  if(effect.type==='CURRENT_HP_DAMAGE'){if(validity.target){const amount=Math.max(1,Math.floor(validity.target.stats.hp*(effect.fraction??0)));const t=validity.target,b=t.stats.hp;t.stats.hp=Math.max(0,b-amount);emit(sim,EVENT_TYPE.DAMAGE,{initiativeCycle:cycle,actorId:actor.unitId,targetId:t.unitId,parentEventId,payload:{amount:b-t.stats.hp,hpBefore:b,hpAfter:t.stats.hp,source:'ABILITY',abilityId:ability.id,damageType:'PERCENT_CURRENT_HP'}});if(t.stats.hp===0&&t.lifeState===LIFE_STATE.ALIVE){markUnitDead(sim.state,t.unitId);updateBattleOutcome(sim.state);emit(sim,EVENT_TYPE.KO,{initiativeCycle:cycle,actorId:actor.unitId,targetId:t.unitId,parentEventId,payload:{position:t.position,source:'ABILITY',abilityId:ability.id}});}}continue;}
  if(effect.type==='LIFE_DRAIN'){lastDamage=applyDamage(sim,actor,validity.target,{...scaledDamageEffect(effect),damageType:DAMAGE_TYPE.MAGICAL,dodgeable:false},cycle,parentEventId,ability.id);if(lastDamage.dealt>0)healTarget(sim,actor,actor,{fixedAmount:lastDamage.dealt},cycle,parentEventId,ability.id);continue;}
  if(effect.type==='POISON_FLAT_ROLL'){for(const t of targetsFor(sim,actor,{to:effect.to},validity)){const base=rollRange(sim,effect.min,effect.max,`POISON_ROLL:${ability.id}:${t.unitId}`);const amount=Math.max(1,Math.floor(base*Math.max(0,effectiveStat(actor,effect.scalesWith??'SDM'))/100));applyPoison(sim,t.unitId,amount,{sourceId:actor.unitId,cycle,parentEventId,abilityId:ability.id});}continue;}
  if(effect.type==='DETONATE_POISON'){const ts=targetsFor(sim,actor,{to:effect.scope},validity);const group=ts.length>1?`${parentEventId??'ROOT'}:${ability.id}:DETONATE`:null;for(const t of ts){const amount=poisonTotal(t);if(amount<=0)continue;removeStatus(t,'poison');const b=t.stats.hp;t.stats.hp=Math.max(0,b-amount);emit(sim,EVENT_TYPE.DAMAGE,{initiativeCycle:cycle,actorId:actor.unitId,targetId:t.unitId,parentEventId,payload:{amount:b-t.stats.hp,hpBefore:b,hpAfter:t.stats.hp,source:'PLAGUE_DETONATION',abilityId:ability.id,damageType:'POISON',...(group?{simultaneousGroup:group}:{})}});}continue;}
  if(effect.type==='DETONATE_POISON_AND_RESEED'){let total=0;const detTargets=targetsFor(sim,actor,{to:effect.scope},validity);const detGroup=detTargets.length>1?`${parentEventId??'ROOT'}:${ability.id}:DETONATE`:null;for(const t of detTargets){const amount=poisonTotal(t);if(amount<=0)continue;total+=amount;removeStatus(t,'poison');const b=t.stats.hp;t.stats.hp=Math.max(0,b-amount);const ev=emit(sim,EVENT_TYPE.DAMAGE,{initiativeCycle:cycle,actorId:actor.unitId,targetId:t.unitId,parentEventId,payload:{amount:b-t.stats.hp,hpBefore:b,hpAfter:t.stats.hp,source:'PLAGUE_DETONATION',abilityId:ability.id,damageType:'POISON',...(detGroup?{simultaneousGroup:detGroup}:{})}});if(t.stats.hp<=0&&t.lifeState===LIFE_STATE.ALIVE){markUnitDead(sim.state,t.unitId);updateBattleOutcome(sim.state);emit(sim,EVENT_TYPE.KO,{initiativeCycle:cycle,actorId:actor.unitId,targetId:t.unitId,parentEventId:ev.eventId,payload:{position:t.position,source:'PLAGUE_DETONATION',abilityId:ability.id}});}}const reseed=Math.max(0,Math.floor(total*(effect.reseedFraction??.5)));const survivors=unitsCanonical(sim).filter(u=>u.side!==actor.side&&u.lifeState===LIFE_STATE.ALIVE);if(reseed>0&&survivors.length){const chosen=survivors.length===1?survivors[0]:sim.rng.choose(survivors,`PLAGUE_RESEED:${actor.unitId}`);const applied=applyPoison(sim,chosen.unitId,reseed,{sourceId:actor.unitId,cycle,parentEventId,abilityId:ability.id});results.push({detonatedTotal:total,reseedAmount:reseed,reseedTargetId:chosen.unitId,reseedApplied:Boolean(applied)});}else results.push({detonatedTotal:total,reseedAmount:0,reseedTargetId:null,reseedApplied:false});continue;}
  if(effect.type==='AOE_DAMAGE'){const center=validity.ground??validity.target?.position??actor.position;const area={...(ability.area??{shape:AREA_SHAPE.SQUARE_3X3}),center};const ts=unitsInArea(sim.state,actor.unitId,area).filter(t=>effect.hostileOnly===true?t.side!==actor.side:effect.friendlyOnly===true?t.side===actor.side:true);const group=`${parentEventId??'ROOT'}:${ability.id}:AOE`;for(const t of ts)lastDamage=applyDamage(sim,actor,t,{...scaledDamageEffect(effect),simultaneousGroup:group},cycle,parentEventId,ability.id);continue;}
  if(effect.type==='MULTI_STRIKE'){for(let i=0;i<(effect.hits??1);i++){if(!validity.target||validity.target.lifeState!==LIFE_STATE.ALIVE)break;lastDamage=applyDamage(sim,actor,validity.target,{...scaledDamageEffect(effect),damageType:DAMAGE_TYPE.PHYSICAL},cycle,parentEventId,`${ability.id}#${i+1}`);results.push({...lastDamage,multiStrikeIndex:i+1});if(lastDamage?.dealt>0&&!lastDamage.killed&&effect.onHitStatus){const t=sim.state.units[lastDamage.targetId];if(t){const os=effect.onHitStatus;const chance=os.chance??1;if(chance>=1||sim.rng.chance(chance,`MULTI_STRIKE_STATUS:${ability.id}:${i+1}:${t.unitId}`))applyStatus(sim,actor,t,{key:os.key,duration:os.duration??1,data:os.data??{}},cycle,parentEventId);}}}continue;}
  if(effect.type==='STUN_OR_DEF_DOWN'){if(validity.target){if(sim.rng.chance(effect.stunChance??.25,`MIND_SHATTER_CC:${actor.unitId}->${validity.target.unitId}`))applyStatus(sim,actor,validity.target,{key:'stun',duration:effect.stunDuration??2},cycle,parentEventId);else applyStatus(sim,actor,validity.target,{key:'def_down',duration:effect.defDownDuration??4},cycle,parentEventId);}continue;}
  if(effect.type==='ON_KILL_STATUS'){if(lastDamage?.killed){for(const t of targetsFor(sim,actor,{to:effect.to??'SELF'},validity))applyStatus(sim,actor,t,{key:effect.key,duration:effect.duration,stackMode:'STACK'},cycle,parentEventId);}continue;}
  if(effect.type==='RESURRECT_OR_HEAL'){const t=validity.target;if(t){if(t.lifeState===LIFE_STATE.DEAD){t.lifeState=LIFE_STATE.ALIVE;t.stats.hp=Math.max(1,Math.floor(t.stats.maxHP*(effect.revivePctMaxHP??.5)));if(effect.cleanse)t.statuses=[];emit(sim,EVENT_TYPE.RESURRECT,{initiativeCycle:cycle,actorId:actor.unitId,targetId:t.unitId,parentEventId,payload:{hp:t.stats.hp,position:t.position,abilityId:ability.id}});}else healTarget(sim,actor,t,{pctMaxHP:effect.livingHealPctMaxHP??.25},cycle,parentEventId,ability.id);}continue;}
  if(effect.type==='TEMP_ATTACKS_MAX'){for(const t of targetsFor(sim,actor,effect,validity)){const amount=Math.max(0,Math.trunc(effect.amount??0));const statusKeyName=effect.statusKey??'attacks_max_up';const existing=findStatus(t,statusKeyName);if(!existing){t.resources.attacksMax+=amount;t.resources.attacksRemaining+=amount;}applyTimedStatus(sim,t.unitId,{key:statusKeyName,duration:effect.duration,sourceId:actor.unitId,data:{amount,resource:'ATTACKS_MAX'},cycle,parentEventId});}continue;}
  if(effect.type==='TEMP_ATTACKS_MULTIPLIER'){const t=effect.to==='SELF'?actor:validity.target;if(t){const factor=Math.max(1,Number(effect.factor??1));const amount=Math.max(0,Math.floor(t.resources.attacksMax*(factor-1)));t.resources.attacksMax+=amount;t.resources.attacksRemaining+=amount;applyTimedStatus(sim,t.unitId,{key:'attacks_max_up',duration:effect.duration,sourceId:actor.unitId,data:{amount,source:'MULTIPLIER',factor,resource:'ATTACKS_MAX'},cycle,parentEventId});}continue;}
  if(effect.type==='TEMP_MOVEMENT_MAX'){for(const t of targetsFor(sim,actor,effect,validity)){const amount=Math.max(0,Math.trunc(effect.amount??0));const statusKeyName=effect.statusKey??'movement_max_up';const existing=findStatus(t,statusKeyName);if(!existing){t.resources.movementMax+=amount;t.resources.movementRemaining+=amount;}applyTimedStatus(sim,t.unitId,{key:statusKeyName,duration:effect.duration,sourceId:actor.unitId,data:{amount,resource:'MOVEMENT_MAX'},cycle,parentEventId});}continue;}
  if(effect.type==='TEMP_MOVEMENT_MULTIPLIER'){const t=effect.to==='SELF'?actor:validity.target;if(t){const factor=Math.max(1,Number(effect.factor??1));const amount=Math.max(0,Math.floor(t.resources.movementMax*(factor-1)));t.resources.movementMax+=amount;t.resources.movementRemaining+=amount;applyTimedStatus(sim,t.unitId,{key:'movement_max_up',duration:effect.duration,sourceId:actor.unitId,data:{amount,source:'MULTIPLIER',factor,resource:'MOVEMENT_MAX'},cycle,parentEventId});}continue;}
  if(effect.type==='SUMMON_FAERY'){if(validity.target)results.push({summon:summonFaery(sim,{ownerId:actor.unitId,targetId:validity.target.unitId,cycle,parentEventId})});continue;}
  if(effect.type==='HYBRID_STORM'){const group=`${parentEventId??'ROOT'}:${ability.id}:STORM`;for(const t of unitsCanonical(sim)){if(t.lifeState!==LIFE_STATE.ALIVE)continue;if(t.side===actor.side)healTarget(sim,actor,t,{...effect.heal,simultaneousGroup:group},cycle,parentEventId,ability.id);else{lastDamage=applyDamage(sim,actor,t,{...scaledDamageEffect(effect.damage),damageType:DAMAGE_TYPE.MAGICAL,scalesWith:'SDM',dodgeable:false,simultaneousGroup:group},cycle,parentEventId,ability.id);if(t.lifeState===LIFE_STATE.ALIVE)applyStatus(sim,actor,t,{key:'stun',duration:1,chance:effect.stunChance},cycle,parentEventId);}}continue;}
  if(effect.type==='CHAIN_LIGHTNING'){let current=validity.target;const hitIds=new Set();while(current&&current.lifeState===LIFE_STATE.ALIVE&&!hitIds.has(current.unitId)){hitIds.add(current.unitId);lastDamage=applyDamage(sim,actor,current,{...scaledDamageEffect(effect),damageType:DAMAGE_TYPE.MAGICAL,scalesWith:'SDM',dodgeable:false},cycle,parentEventId,ability.id);const candidates=unitsCanonical(sim).filter(u=>u.lifeState===LIFE_STATE.ALIVE&&!hitIds.has(u.unitId));if(!candidates.length||!sim.rng.chance(effect.bounceChance??.65,`CHAIN_BOUNCE:${actor.unitId}:${hitIds.size}`))break;current=candidates[sim.rng.nextInt(0,candidates.length-1,`CHAIN_TARGET:${actor.unitId}:${hitIds.size}`)];}continue;}
 }
 return results;
}
